### ISSUE TITLE
初始 TSC 成员提名

### ISSUE THREAD

**Issue by wssgcg1213** [openkraken/TSC#1]
按照[规则](https://github.com/openkraken/kraken/blob/main/GOVERNANCE.zh-CN.md)，提名第一次 TSC 成员名单

**Comment by wssgcg1213** [comment]
@wssgcg1213 @yuanyan @andycall @answershuto @qinxuliang

**Comment by whn9527** [comment]
@whn9527

**Comment by wssgcg1213** [comment]
@temper357 @tylorvan

**Comment by wssgcg1213** [comment]
名单详见 Group Member @openkraken/tsc 列表
