### ISSUE TITLE
TSC的会议是不定时召开的吗

### ISSUE THREAD

**Issue by cnryb** [openkraken/TSC#12]
我开会议记录里的时间并没有什么规律，而且两个多月没见你们新的会议记录了。你们不考虑一下定时会议什么的吗？

**Comment by andycall** [comment]
@wssgcg1213

**Comment by wssgcg1213** [comment]
是定时召开的   
定时会议是个好想法, 比如提前确定至少 3 次会议的时间, 使用类似搭火车的方式

**Comment by cnryb** [comment]
#13 👍
