### ISSUE TITLE
推荐 @cnryb 加入 Kraken TSC

### ISSUE THREAD

**Issue by answershuto** [openkraken/TSC#20]
Hi，All ， @openkraken/collaborators 。

推荐 @cnryb 进入 Kraken TSC，下面是 @cnryb 的一些贡献。

在 [openkraken/kraken](https://github.com/openkraken/kraken) 仓库中提交的 Pull requests ： [https://github.com/openkraken/kraken/pull/557](https://github.com/openkraken/kraken/pull/557)

在 [openkraken/kraken](https://github.com/openkraken/kraken) 仓库中提交的 Pull requests ： [https://github.com/openkraken/kraken/pull/540](https://github.com/openkraken/kraken/pull/540)

**Comment by andycall** [comment]
+1

**Comment by wssgcg1213** [comment]
Waiting for 7 days, if no TSC member reject, the approval will be automatically accepted.

**Comment by wssgcg1213** [comment]
Welcome!
