### ISSUE TITLE
推荐 @airingursb 加入 Kraken TSC

### ISSUE THREAD

**Issue by answershuto** [openkraken/TSC#21]
Hi，All ， @openkraken/collaborators 。

推荐 @airingursb 进入 Kraken TSC，下面是 @airingursb 的一些贡献。

在 [openkraken/kraken](https://github.com/openkraken/kraken) 仓库中提交的 Pull requests ： [https://github.com/openkraken/kraken/pull/629](https://github.com/openkraken/kraken/pull/629)

在 [openkraken/kraken](https://github.com/openkraken/kraken) 仓库中提交的 Pull requests ： [https://github.com/openkraken/kraken/pull/463](https://github.com/openkraken/kraken/pull/463)

在 [openkraken/kraken](https://github.com/openkraken/kraken) 仓库中提交的 Pull requests ： [https://github.com/openkraken/kraken/pull/320](https://github.com/openkraken/kraken/pull/320)

在 [openkraken/kraken](https://github.com/openkraken/kraken) 仓库中提交的 Pull requests ： [https://github.com/openkraken/kraken/pull/249](https://github.com/openkraken/kraken/pull/249)

在 [openkraken/kraken](https://github.com/openkraken/kraken) 仓库中提交的一系列 Issue ： [https://github.com/openkraken/kraken/issues?q=is%3Aissue+author%3Aairingursb+](https://github.com/openkraken/kraken/issues?q=is%3Aissue+author%3Aairingursb+)

**Comment by andycall** [comment]
+1

**Comment by wssgcg1213** [comment]
Waiting for 7 days, if no TSC member reject, the approval will be automatically accepted.

**Comment by wssgcg1213** [comment]
Welcome!
