### ISSUE TITLE
推荐 @anjihang 加入 Kraken TSC

### ISSUE THREAD

**Issue by andycall** [openkraken/TSC#23]
Hi，All ， @openkraken/collaborators 。

推荐 @anjihang 进入 Kraken TSC，下面是 @anjihang 的一些贡献。

在 openkraken/kraken 仓库中提交的 Pull requests ： 

https://github.com/openkraken/kraken/pulls?q=is%3Apr+author%3Aanjihang

**Comment by answershuto** [comment]
+1

**Comment by wssgcg1213** [comment]
Waiting for 7 days, if no TSC member reject, the approval will be automatically accepted.

**Comment by wssgcg1213** [comment]
Welcome!
