### ISSUE TITLE
OpenKraken Technical Steering Committee (TSC) Meeting 2021-11-25

### ISSUE THREAD

**Issue by andycall** [openkraken/TSC#28]
Hi all, 以下是 TSC 会议邀约, 请根据自己的时间确定是否参加

议程可以通过提出 issue 增加 tsc tag 的形式新增，本次会议新增议程截止时间为： 2021-11-25 19:15

会议形式为钉钉视频在线会议，结束后会议纪要将同步到本仓库。

时间
UTC+8 北京时间 22021-11-25 19:15

Agenda

**Comment by andycall** [comment]
1. 有关 Kraken 加载本地 assets 文件的讨论
2. Kraken 混合 Widget 方案设计

**Comment by cnryb** [comment]
还有期待很久的 road map
