### ISSUE TITLE
性能、包体积、内存等目标以及长期的目标?

### ISSUE THREAD

**Issue by wssgcg1213** [openkraken/TSC#4]

**Comment by andycall** [comment]
Kraken 0.7

性能：

1. 滚动帧率
在低端 Android 机器上也可以实现 50-60 FPS 滚动

2. 首屏加载时间
-

包体积增量：

1. libkraken_jsc.so  (886.1 KB)
2. libapp.so （5.5MB) （相比最简单的 flutter 项目）
3. libjsc.so (8.8MB)

内存：
-

**Comment by wssgcg1213** [comment]
1. 低端机体感 50fps
2. 首屏渲染时间 
     - 冷启 < WebView 20%
     - 热启 < WebView 30%
3. 内存
     - 增量 < WebView 50%
     - 峰值 < +100%
4. 包体积
     - Dart+Bridge app 增量 iOS 1.5M Android 1M
     - 支持 qjs

**Comment by cnryb** [comment]
@andycall @wssgcg1213 不知道两位得到这些数据的方法是什么。最新版本的 kraken （0.8.1）的数据又是什么样的呢
