### ISSUE TITLE
推荐 @pba-cra 加入 Kraken TSC

### ISSUE THREAD

**Issue by answershuto** [openkraken/TSC#43]
Hi，All ， https://github.com/orgs/openkraken/teams/collaborators 。

推荐 @pba-cra 进入 Kraken TSC，下面是 @pba-cra 的一些贡献。

在 openkraken/plugins 中提交的 Pull requests ：

https://github.com/openkraken/plugins/pull/32

**Comment by wssgcg1213** [comment]
经 TSC 会议通过, Approved
