### ISSUE TITLE
社区开发者共建 Kraken 报名

### ISSUE THREAD

**Issue by answershuto** [openkraken/TSC#47]
为了后续继续将 Kraken 维护下去，希望有社区开发者可以投入来一起建设好 Kraken。
Kraken TSC 的同学也会继续投入在这个事情上给予技术支持与指导，原团队部分同学会继续投入开发。
欢迎有想法的同学在此报名并自我介绍以及留下自己的联系方式，后续我们希望可以继续推进这个事情。

**Comment by andycall** [comment]
+1

**Comment by yifei8** [comment]
+1

**Comment by xuzhongpeng** [comment]
报名+1，目前在阿里云做客户端开发，有前端、Flutter相关经验，花名幺风

**Comment by pba-cra** [comment]
+1

**Comment by classtimetable** [comment]
+1

**Comment by airingursb** [comment]
+1，目前在腾讯音乐做 Web 前端开发，有 Web、iOS、Flutter 相关经验，ID: Airing。
今后依然抽个人时间跟进&共享项目

**Comment by suyulin** [comment]
+1，目前在欧瑞博科技任职，有Flutter 、web、go、嵌入式相关经验，愿意使用个人时间维护Kraken。

**Comment by andycall** [comment]
@suyulin @tianya8318 @airingursb  @classtimetable  @pba-cra @xuzhongpeng @yifei8 

麻烦更新一下邮箱地址，我后续给你们发送 TSC 邀请邮件

**Comment by devjiangzhou** [comment]
+1, iOS 开发，有 Flutter、web 相关经验,
mail: jiangzhobuai@gmail.com

**Comment by airingursb** [comment]
> @suyulin @tianya8318 @airingursb @classtimetable @pba-cra @xuzhongpeng @yifei8
> 
> 麻烦更新一下邮箱地址，我后续给你们发送 TSC 邀请邮件

@andycall mail: airing@ursb.me，目前应该已经在组织里了

**Comment by Smarking** [comment]
+1,  Android开发有渲染引擎、Flutter工程经验, smarkingzhao@gmail.com
目前就职于阿里，可利用个人时间维护

**Comment by XGHeaven** [comment]
mail: xgheaven@gmail.com
自我介绍：目前就职于字节跳动，主要负责飞书小程序引擎 JS 侧相关的开发。对整体的 Web 标准有一些简单的了解，以及一些简单的 qjs 和 native 开发经验。
日后也主要利用个人时间维护

**Comment by dancancer** [comment]
+1，前端开发，有 Web、 Flutter 相关经验，可使用个人时间维护Kraken，dan.cancer@gmail.com

**Comment by yuanyan** [comment]
+1，会参与CR，大家可以 @ 我

**Comment by temper357** [comment]
+1 
Kraken Core Contributor，已从阿里离职，目前在找工作中。

278615001@qq.com

**Comment by jwxbond** [comment]
> +1，会参与CR，大家可以 @ 我

+1

**Comment by andycall** [comment]
@jwxbond 请提供一下个人邮箱

**Comment by andycall** [comment]
会议邮件邀请已发送。

@jwxbond @pba-cra 请提供一下邮件地址，不然我没法给你们发送会议邀请
