### ISSUE TITLE
Kraken加载流程优化，支持多线程，并行任务执行

### ISSUE THREAD

**Issue by tylorvan** [openkraken/TSC#7]
期望增加Kraken支持多线程，flutter 的 Future 任务存在排队，被Flutter 调度
建议增加一个独立的kraken 子线程任务体系，可以并行任务执行，可以提前进行请求、加载、初始化JS 环境

1. isolate 方案？
2.端/引擎增加子线程？

**Comment by andycall** [comment]
将 JS 与布局绑定的这种单线程设计对于渲染链路是最好的设计方案，这个已经被各种跨平台渲染架构（flutter，浏览器）所验证。而像 RN 这种将 JS 与 UI 线程独立所带来的通信问题也非常明显。Kraken 不打算走 RN 的老路，而是 Follow 其他成熟渲染系统的架构设计。
不过，单个页面采用单线程架构没有问题，对于多个 Kraken 页面，是否可以采取多 Flutter Engine 实例的方式进行解决？
我会先发起一个  TSC 讨论

**Comment by wssgcg1213** [comment]
https://github.com/openkraken/TSC/blob/master/meetings/2021-03-31.md
0331 TSC 讨论中提出浏览器的 Worker 模型可能是一个比较有可行性的方案

**Comment by wssgcg1213** [comment]
转移到 https://github.com/openkraken/kraken/issues/310 继续讨论
